version: 2
updates:
- package-ecosystem: npm
  directory: "/app"
  schedule:
    interval: daily
    time: '00:00'
  open-pull-requests-limit: 99
  reviewers:
    - maurosbicego
  assignees:
    - maurosbicego
  labels:
    - dependencies
  commit-message:
    prefix: fix
    prefix-development: chore
    include: scope

- package-ecosystem: pip
  directory: "/api"
  schedule:
    interval: daily
    time: '00:00'
  open-pull-requests-limit: 99
  reviewers:
    - maurosbicego
  assignees:
    - maurosbicego
  labels:
    - dependencies
  commit-message:
    prefix: fix
    prefix-development: chore
    include: scope
