version: '3'

services:
  db:
    image: mongo:3.6.20-xenial
    ports:
      - '127.0.0.1:27017:27017'
    network_mode: 'host'
    restart: always
  api:
    build:
      dockerfile: Dockerfile
      context: api
    image: rowmate:api
    env_file:
      - api/.env
    depends_on:
      - db
    ports:
      - '127.0.0.1:8000:8000'
    network_mode: 'host'
  app:
    build:
      dockerfile: Dockerfile
      context: app
    image: rowmate:app
    env_file:
      - app/.env
    depends_on:
      - api
    ports:
      - '127.0.0.1:3000:3000'
    network_mode: 'host'
